version: '3'

services:
  app:
    build: .
    volumes:
      - ./outputs:/outputs
    depends_on:
      - db
    environment:
      # Consider adding environment variables from a separate file (.env) for security
      - PYTHONUNBUFFERED=1  # Optional: Prevent output buffering in Python (can improve performance)

  db:
    image: postgres:12-alpine  # Use a lightweight Alpine-based image
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1333
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: